version: '2'

services:
  db:
    image: postgres
    volumes:
    - ./tmp/db:/var/lib/postgresql
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  backend:
    build:
      context: ./backend/community
      dockerfile: Dockerfile
    ports:
    - 4000:4000
    depends_on:
    - db
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - 3000:3000
    volumes:
    - ./frontend:/usr/src/app/:rw
    environment:
    - NODE_ENV=dev
    depends_on:
    - backend
